apiVersion: v1
kind: ConfigMap
metadata:
  name: docuflow-config
  namespace: docuflow
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  MINIO_ENDPOINT: "http://minio:9000"
  GRPC_PORT: "9090"
---
apiVersion: v1
kind: Secret
metadata:
  name: docuflow-secrets
  namespace: docuflow
type: Opaque
stringData:
  DATABASE_URL: "jdbc:postgresql://postgres:5432/docuflow_core"
  DATABASE_USER: "docuflow"
  DATABASE_PASSWORD: "changeme"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "changeme"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "changeme"
  OAUTH2_ISSUER_URI: "https://auth.docuflow.io/realms/docuflow"
  OAUTH2_JWK_SET_URI: "https://auth.docuflow.io/realms/docuflow/protocol/openid-connect/certs"