apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docuflow

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: docuflow-core
      spec:
        replicas: 2
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: docuflow-integrations
      spec:
        replicas: 2
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: docuflow-api
      spec:
        replicas: 3
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: docuflow-ml
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: docuflow-ml
                resources:
                  requests:
                    memory: "8Gi"
                    cpu: "2000m"
                  limits:
                    memory: "16Gi"
                    cpu: "4000m"